### ISSUE TITLE
example code?

### ISSUE THREAD

**Issue by sunkr1995** [Topaceminem/DCC-GARCH#1]
hello,
    thank you for your working,But i dont know how to use these API,
    Could you add some example code ?
                            thank you

**Comment by Topaceminem** [comment]
Thanks for reaching out and sorry for my late response as I was totally occupied last month. 

I have updated an example on the repository. The ipynb file can be directly opened on the GitHub web but some LaTeX codes used to write formula aren't displayed well. Therefore, you are more recommended to download the HTML file and open it in your Google browser (refresh twice if garbled) for a better reading experience. 

In the meantime, I have updated a refined version of DCC_GARCH. Note that some parts of the code are still experimental, as I haven't implemented public API for them. If you want to use DCC_GARCH, for the time being, the best way is to download the whole package to your local project so that you can import it directly. You can also copy the code but please kindly leave a footnote such as “Author: @ Suoer Xu, github.com/Topaceminem” under the copy.
